name: pattern-rec
channels:
  - defaults
dependencies:
  - absl-py=2.1.0
  - aom=3.6.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - eigen=3.4.0
  - executing=2.2.1
  - expat=2.7.1
  - flatbuffers=24.3.25
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gast=0.6.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.71.0
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - h5py=3.14.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=73.1
  - idna=3.7
  - intel-openmp=2025.0.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keras=3.11.2
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libcurl=8.15.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.16
  - libkrb5=1.21.3
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.5.1
  - mpi=1.0
  - mpi4py=4.0.3
  - msmpi=10.1.1
  - msys2-conda-epoch=20160418
  - namex=0.1.0
  - nest-asyncio=1.6.0
  - numexpr=2.11.0
  - numpy=2.1.3
  - numpy-base=2.1.3
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.0.18
  - opt_einsum=3.3.0
  - optree=0.14.1
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.4
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=5.29.3
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python-tzdata=2025.2
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2024.07.02
  - requests=2.32.5
  - rich=13.9.4
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.19.1
  - tensorflow-base=2.19.1
  - termcolor=2.1.0
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.42
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
